apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: wise2017
  POSTGRES_PASSWORD: wise2017
  POSTGRES_DB: n8n
  POSTGRES_NON_ROOT_USER: wise2017
  POSTGRES_NON_ROOT_PASSWORD: wise2017